version: '3'

services:
  helloworld:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/opt/helloworld/app
    ports:
      - "8000:8000"
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/opt/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.templates=/etc/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.no-lockfile"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    ports:
      - 3000:3000
volumes:
  prometheus_data:
  grafana_data:
