---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: helloworldcloud
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: helloworldcloud
  minReplicas: 3
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
