---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: helloworldcloud
  name: helloworldcloud
spec:
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: helloworldcloud
    spec:
      containers:
      - args:
        - "python"
        - "manage.py"
        - "runserver"
        - "0.0.0.0:8000"
        image: quay.io/neegor/helloworldcloud:v-20190311
        name: helloworldcloud
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        resources:
          requests:
            memory: "1Gi"
            cpu: "200m"
          limits:
            memory: "2Gi"
            cpu: "250m"
status: {}

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    service: helloworldcloud
  name: helloworldcloud
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30011
    protocol: TCP
  selector:
    service: helloworldcloud
status:
  loadBalancer: {}
