---

apiVersion: batch/v1
kind: Job
metadata:
  name: helloworldcloud-migrate
spec:
  backoffLimit: 2
  template:
    metadata:
      name: helloworldcloud-migrate
    spec:
      containers:
      - name: helloworldcloud
        image: quay.io/neegor/helloworldcloud:v-20190311
        command:
         - "python"
         - "manage.py"
         - "migrate"
         - "--noinput"
      restartPolicy: Never

---

apiVersion: batch/v1
kind: Job
metadata:
  name: helloworldcloud-collectstatic
spec:
  backoffLimit: 2
  template:
    metadata:
      name: helloworldcloud-collectstatic
    spec:
      containers:
      - name: helloworldcloud
        image: quay.io/neegor/helloworldcloud:v-20190311
        command:
         - "python"
         - "manage.py"
         - "collectstatic"
         - "--noinput"
      restartPolicy: Never
